matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.3
language: csharp
mono: latest
dotnet: 2.1.105
before_install:
  - bash fetch_native.sh
script: 
  - unset DOTNET_CLI_TELEMETRY_OPTOUT
  - dotnet build -c Release
  - dotnet test -c Release UnitTests/UnitTests.csproj 
  - dotnet pack -c Release
  - dotnet nuget locals all --clear
  - dotnet run -p NugetTest
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_OS_NAME" = "linux" ] ; then bash doc/build.sh ; fi  
deploy:
  - provider: script
    script: bash deploy.sh
    skip-cleanup: true
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
  - provider: pages
    local-dir: doc/_site
    skip-cleanup: true
    target-branch: gh-pages
    github-token: $GITHUB_TOKEN  
    keep-history: true
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
