matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.3
language: csharp
mono: none
dotnet: 2.1.105
solution: HDF.PInvoke.sln
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo rm '/usr/local/include/c++' ; brew update ; brew install hdf5 ; fi
script: 
  - unset DOTNET_CLI_TELEMETRY_OPTOUT
  - dotnet build -c Release
  - dotnet test -c Release UnitTests/UnitTests.csproj
  - dotnet pack -c Release
  - cd NugetTest ; dotnet nuget locals all --clear ; dotnet run
# deploy:
#   - provider: script
#     script: bash deploy.sh
#     skip-cleanup: true
#     on:
#       condition: $TRAVIS_OS_NAME = linux
 