matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode9.3
language: csharp
mono: none
dotnet: 2.1.105
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo rm '/usr/local/include/c++' ; brew update ; brew install hdf5 ; fi
  - bash fetch_native.sh
  script: 
  - unset DOTNET_CLI_TELEMETRY_OPTOUT
  - dotnet build -c Release
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then dotnet test -c Release UnitTests/UnitTests.csproj ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then dotnet test -c Release UnitTests/UnitTests.csproj || true; fi
  - dotnet pack -c Release
  - dotnet nuget locals all --clear
  - dotnet run -p NugetTest
deploy:
  - provider: script
    script: bash deploy.sh
    skip-cleanup: true
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
 