version: 1.0.{build}
image: Visual Studio 2017

build_script:
  - dotnet build -c Release

test_script:
  - dotnet test -c Release UnitTests/UnitTests.csproj

after_test:
  - dotnet pack -c Release
  - cd NugetTest ; dotnet nuget locals all --clear ; dotnet run

artifacts:
  - path: bin\Release\*.nupkg
