version: 1.0.{build}
image: Visual Studio 2017

build_script:
  - dotnet build -c HDF5_1.10_Release

test_script:
  - dotnet test -c HDF5_1.10_Release UnitTests/UnitTests.csproj

after_test:
  - dotnet pack -c HDF5_1.10_Release

artifacts:
  - path: bin\HDF5_1.10_Release\*.nupkg
